# Generated by Django 4.1 on 2024-05-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookcategory_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='category_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookcode',
            name='code_id',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
